call lexima#add_rule({'at': '\%#\w', 'char': '(', 'input': '('})
call lexima#add_rule({'at': '\%#\w', 'char': '[', 'input': '['})
" call lexima#add_rule({'at': '\%#\w', 'char': '{', 'input': '{'})
call lexima#add_rule({'at': '\%#\w', 'char': '"', 'input': '"'})
call lexima#add_rule({'at': '\%#\w', 'char': '''', 'input': ''''})
call lexima#add_rule({'at': '\%#\w', 'char': '`', 'input': '`'})
